name: Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: [ dev, prod ]
        required: true
        description: Choose Env
      action:
        type: choice
        options: [ apply, destroy ]
        required: true
        description: Choose action

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.action }} (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_scaleway_access_key }}
          TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_scaleway_secret_key }}
          TF_VAR_scaleway_project_id: ${{ secrets.TF_VAR_scaleway_project_id }}
          TF_VAR_scaleway_region: ${{ secrets.TF_VAR_scaleway_region }}
          TF_VAR_scaleway_zone: ${{ secrets.TF_VAR_scaleway_zone }}
          TF_VAR_ghcr_username: ${{ secrets.TF_VAR_ghcr_username }}
          TF_VAR_ghcr_pat: ${{ secrets.TF_VAR_ghcr_pat }}
          TF_VAR_ghcr_email: ${{ secrets.TF_VAR_ghcr_email }}
